---
title: "Homework 4: websites + plotly"
author: "Isabel Nelson"
date: "10/27/2020"
output: html_document
---
## Questions from video lectures
- How do you remove a website once it's made on github? 

## Homework instructions
Problem 1
Create a personal website at <YOUR_GH_NAME>.github.io (or some other reasonably-named location). This page can be as extensive as you’d like, but it should include at least:

A brief introductory landing page
A page giving your academic and professional experience (i.e. a resume)
Links in the site navigation for your GitHub account, your email, and other professional networks.  

Problem 2
Create a flexdashboard using plotly for that includes at least three distinct plot types (e.g. scatterplots, line plots, bar plots, box plots, etc.). Use one of the following datasets, and load from the p8105.datasets package:

Instacart
NY NOAA
NYC Restaurant Inspections
These datasets are large; you may want / need to filter or randomly sample from the complete dataset to ensure a reasonable product.

