---
title: "NY Climate Dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme: cosmo
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

```

```{r}
data("ny_noaa")
ny_noaa_df <- 
  ny_noaa %>% 
  filter(id %in% c("USW00094728", "USW00014771")) %>% 
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>% 
  mutate(
    tmax = as.numeric(tmax)/10,
    tmin = as.numeric(tmin)/10,
    station = recode(
      id, 
      USW00094728 = "New_York_City", 
      USW00014771 = "Syracuse"))

```

Column {data-width=350}
-----------------------------------------------------------------------

### Average Max Temperature

```{r}
x_axis <- list(
  nticks = 12,
  title = "Month")

y_axis <- list(
  title = "Average Maximum Temperature (C)")

ny_noaa_df %>% 
  group_by(station, year, month) %>% 
  summarize(
    mean_tmax = round(mean(tmax, na.rm = TRUE))) %>% 
  mutate(text_label = str_c("Month:", month, "\nTemp:", mean_tmax, "(C)")) %>%  
  plot_ly(
    x = ~month, y = ~mean_tmax, color = ~station, text = ~text_label,
    alpha = .8, type = "scatter", mode = "lines", colors = "Dark2") %>% 
  layout(
    xaxis = x_axis, 
    yaxis = y_axis)
```

### Average Min Temperature

```{r}
x_axis <- list(
  nticks = 12,
  title = "Month")

y_axis <- list(
  title = "Average Minimum Temperature (C)")

ny_noaa_df %>% 
  group_by(station, year, month) %>% 
  summarize(
    mean_tmin = round(mean(tmin, na.rm = TRUE))) %>% 
  mutate(text_label = str_c("Month:", month, "\nTemp:", mean_tmin, "(C)")) %>% 
  plot_ly(
    x = ~month, y = ~mean_tmin, color = ~station, text = ~text_label,
    alpha = .8, type = "scatter", mode = "lines", colors = "Dark2") %>% 
  layout(
    xaxis = x_axis, 
    yaxis = y_axis)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Average Precipitation by Month

```{r}
x_axis <- list(
  nticks = 12,
  title = "Month")

y_axis <- list(
  title = "Average Precipitation (mm)")

ny_noaa_df %>% 
  group_by(station, month) %>% 
  summarize(
    mean_prcp = round(mean(prcp, na.rm = TRUE))) %>% 
  mutate(text_label = str_c("Month:", month, "\nPrecipitation:", mean_prcp, "(C)")) %>% 
  plot_ly(
    x = ~month, y = ~mean_prcp, color = ~station, text = ~text_label,
    alpha = .8, type = "bar", colors = "Dark2") %>% 
  layout(
    xaxis = x_axis, 
    yaxis = y_axis)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Distribution of Precipitation - Syracuse

```{r}
x_axis <- list(
  title = "Precipitation (mm)")

y_axis <- list(
  title = "Count")

ny_noaa_df %>% 
  filter(snow != 0) %>% 
  filter(station == "Syracuse") %>% 
plot_ly(alpha = 0.8) %>%
  add_histogram(
    x = ~prcp, 
    name = "Precipitation", 
    color = "Green") %>%        
  add_histogram(
    x = ~snow, 
    name = "Snowfall") %>%    
  layout(
    barmode = "overlay", 
    xaxis = x_axis, 
    yaxis = y_axis)
```

### Distribution of Precipitation - NYC

```{r}
x_axis <- list(
  title = "Precipitation (mm)")

y_axis <- list(
  title = "Count")

ny_noaa_df %>% 
  filter(snow != 0) %>% 
  filter(station == "New_York_City") %>% 
plot_ly(alpha = 0.8) %>%
  add_histogram(
    x = ~prcp, 
    name = "Precipitation", 
    color = "Green") %>%        
  add_histogram(
    x = ~snow, 
    name = "Snowfall") %>%    
  layout(
    barmode = "overlay", 
    xaxis = x_axis, 
    yaxis = y_axis)
```

